// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-FmpQ7mEkt96pHju22S_jiK7RNG3ZkX8',
    appId: '1:319516291992:web:9ae20352abf0ba7d9b71ed',
    messagingSenderId: '319516291992',
    projectId: 'opensource-88def',
    authDomain: 'opensource-88def.firebaseapp.com',
    databaseURL: 'https://opensource-88def-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'opensource-88def.firebasestorage.app',
    measurementId: 'G-49VW71HK95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpioLmYWYDXciG9QRAIjbgjlvRCeOXXMo',
    appId: '1:319516291992:android:4e84259e19b990459b71ed',
    messagingSenderId: '319516291992',
    projectId: 'opensource-88def',
    databaseURL: 'https://opensource-88def-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'opensource-88def.firebasestorage.app',
  );
}
